language: node_js
node_js :
  - "12.16.3"
script :
  - echo "deploying"
install:
  - npm install -g firebase-tools
after_success:
  - npm install && npm run build && npm run generate && firebase deploy --token $FIREBASE_TOKEN
